version: "3.9"

services:
  openwifi1:
    image: <dockerhub-username>/openwifi-x86:latest    # or your local image
    container_name: openwifi1
    network_mode: host                         # same network namespace as host
    privileged: true                           # can manage ip/nftables/routes
    #restart: always
    tty: true
    stdin_open: true
    volumes:
      - /lib/modules:/lib/modules:ro
      - /home/<username>/WORKSPACE/OPENWIFI-X86/certs/cert.pem:/etc/ucentral/cert.pem:ro
      - /home/<username>/WORKSPACE/OPENWIFI-X86/certs/key.pem:/etc/ucentral/key.pem:ro
      - /home/<username>/WORKSPACE/OPENWIFI-X86/certs/cas.pem:/etc/ucentral/cas.pem:ro
      - /home/<username>/WORKSPACE/OPENWIFI-X86/certs/gateway.json:/etc/ucentral/gateway.json:ro
      - /home/<username>/WORKSPACE/OPENWIFI-X86/scripts/openwifi-health.sh:/usr/local/bin/openwifi-health.sh:ro
    dns:
      - 127.0.0.1
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/openwifi-health.sh"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 40s

